spring.application.name=reservation

# database
spring.datasource.url=jdbc:sqlite:restaurant.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# login
spring.security.user.name=user
spring.security.user.password=user

# restaurant zones
restaurant.zones[0].name=QUIET
restaurant.zones[0].bounds.xMin=4
restaurant.zones[0].bounds.xMax=6
restaurant.zones[0].bounds.yMin=3
restaurant.zones[0].bounds.yMax=6

restaurant.zones[1].name=CHILDREN
restaurant.zones[1].bounds.xMin=1
restaurant.zones[1].bounds.xMax=3
restaurant.zones[1].bounds.yMin=3
restaurant.zones[1].bounds.yMax=6

restaurant.zones[2].name=TERRACE
restaurant.zones[2].bounds.xMin=1
restaurant.zones[2].bounds.xMax=6
restaurant.zones[2].bounds.yMin=1
restaurant.zones[2].bounds.yMax=2

# restaurant open-close time
restaurant.openTime=10:00
restaurant.closeTime=21:00
restaurant.timeZone=UTC